### ISSUE TITLE
Plone 5 meta ticket

### ISSUE THREAD

**Issue by svx** [plone/documentation#198]
- [x] remove old-reference-manuals/plone_3_theming ?
- [x] remove old-reference-manuals/pluggable_authentication_service ? 
- [x] remove old-reference-manuals/portlets/ ?
- [x] remove old-reference-manuals/testing ?
- [x] remove old-reference-manuals/zope_secrets/ ?
- [x] remove old-reference-manuals/old-style-vs-new-style
- [x] remove old-reference-manuals/forms/ ?
- [x] remove old-reference-manuals/formlib ?
- [x] remove old-reference-manuals/buildout/ ?
- [x] remove old-reference-manuals/archgenxml ?
- [x] remove old-reference-manuals/archetypes/ ?
- [x] update working with content with new UX
- [x] include plone.api in core docs, not as external anymore
- [ ] #215 
- [x] #184 
- [x] #217 
- [x] #235
- [x] cleanup all old paster/zopeskel docs
- [x] add UI-installer docs
- [ ] add vagrant docs
- [ ] add virtualbox docs
- [ ] more

As a 'general' rule of thumb, we should merge all issues, which are still valid for Plone 4 also back into the docs for Plone 4

**Check always: training.plone.org/5** for examples !!

**Comment by miohtama** [comment]
Just for the reference: Please leave the material accessible online somewhere (even in the github in source form). Some poor people are still maintaining those old Plone 3 sites and need to take look on these from time to time.

**Comment by svx** [comment]
Looks like your are not up to date anymore :)
These docs **will stay online**, there are anyway in the docs of plone 3 [docs.plone.org/3.3] and there are also in the plone 4 docs, which will be move to docs.plone.org/4.something.
So they will stay online :)
But I want to remove them from the 5 docs, which will be later docs.plone.org/ :)

**Comment by svx** [comment]
can be closed
