### ISSUE TITLE
Meta: Improve  writing/docs styleguide

### ISSUE THREAD

**Issue by svx** [plone/documentation#879]
# Abstract
Currently our style-guide is kind of a mess :)

- bad structured
- hard to read
- confusing
- missing important things

# Solution

Rewrite and split into sections with better structure, make a better split between docs on docs.plone.org and documentation for add-ons.

- general/overview
- writing/tone
- add missing info from: 
  - [ ] https://github.com/plone/documentation/issues/747
  - [ ] https://github.com/plone/documentation/issues/802
  - [ ] https://github.com/plone/documentation/issues/818
- improve wording
