### ISSUE TITLE
Meta Ticket: Improve theming docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#968]
There are a couple of issues with the whole theming chapter :)

- [ ] how accurate are the docs are for Plone 5.x  
- [ ] wording
- [ ] images and pdfs should move to the _static and/or download folder
- [ ] reST
- [ ] some parts here never got updated for Plone 5.x (like there are still mention Plone 4.x, only)

One thing what jumped into my eye for example is: https://docs.plone.org/adapt-and-extend/theming/quick_test.html

**Do not get me wrong !!!**

I am really thankful that someone took the time for adding it, but in the current state all documentation tests are failing on this part :)

- tone
- wording
- reST
- structure
- location of files
- consistency

:)

**Comment by stevepiercy** [comment]
Closing now that we use Plone Sphinx Theme.
